### ISSUE TITLE
Use `udt_name` for `USER-DEFINED` data types as the generator key

### ISSUE THREAD

**Issue by alleneubank** [isaacharrisholt/supawright#5]
Our database uses quite a large number of `USER-DEFINED` data types in postgres such as `enum` and `citext`. This forces all of them to be handled by one `USER-DEFINED` generator function. 

Consider using the `udt_name` when building the tree and using that as the key for the generator function. [Reference.](https://www.postgresql.org/docs/current/infoschema-columns.html#:~:text=data_type%20character_data,domain_name%20and%20associated%20columns).)

https://github.com/isaacharrisholt/supawright/blob/main/src/tree.ts#L42

That will also allow you to join on the possible enum values.

```sql
select table_name, column_name, data_type, udt_name
from information_schema.columns
where table_schema in (${schemasString});
```

```sql
-- pull all enum values in a schema
select n.nspname as enum_schema,
       t.typname as enum_name,
       e.enumlabel as enum_value
from pg_type t
         join pg_enum e on t.oid = e.enumtypid
         join pg_catalog.pg_namespace n ON n.oid = t.typnamespace
where n.nspname in (${schemasString});
```

**Comment by isaacharrisholt** [comment]
I'd be happy for a change like this to be made! Unfortunately, I don't have huge amounts of time at the minute, but I'd be open to reviewing a PR.

It would have to be backwards-compatible though - I don't fancy a new version number just yet.

**Comment by isaacharrisholt** [comment]
Hey @0xBigBoss this should now be much easier. Supawright 0.2.0 can automatically infer enums from the DB, and if your `USER-DEFINED` generator returns `null` or `undefined`, this is the behaviour it'll fall back to.
